development:
  adapter: postgresql
  encoding: unicode
  database: fake
  host: localhost
  user: jimneath

test:
  adapter: postgresql
  encoding: unicode
  database: fake_test
  host: localhost
  user: jimneath

production:
  adapter: postgresql
  encoding: unicode
  database: fake
  host: localhost
  user: jimneath